import { 
  Loader2, 
  Copy, 
  Check, 
  Download,
  School,
  User,
  Home,
  LogOut,
  Settings,
  FileText,
  BookOpen,
  Award,
  CreditCard,
  Calendar,
  Users,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  X,
  Menu,
  Search,
  Plus,
  Trash,
  Edit,
  Eye,
  Mail,
  Phone,
  Image,
  CloudUpload,
  AlertTriangle,
  CheckCircle,
  XCircle,
  Info,
  HelpCircle
} from 'lucide-react';

export const Icons = {
  spinner: Loader2,
  copy: Copy,
  check: Check,
  download: Download,
  school: School,
  user: User,
  home: Home,
  logout: LogOut,
  settings: Settings,
  fileText: FileText,
  bookOpen: BookOpen,
  award: Award,
  creditCard: CreditCard,
  calendar: Calendar,
  users: Users,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  close: X,
  menu: Menu,
  search: Search,
  add: Plus,
  delete: Trash,
  edit: Edit,
  view: Eye,
  mail: Mail,
  phone: Phone,
  image: Image,
  upload: CloudUpload,
  warning: AlertTriangle,
  success: CheckCircle,
  error: XCircle,
  info: Info,
  help: HelpCircle
};